### ISSUE TITLE
Application JavaScript should occupy only one global variable

### ISSUE THREAD

**Issue by brettmclean** [mromphf/blackjack#1]
The app should avoid placing more than one variable in the JavaScript global namespace. It currently exposes more functions this way than are necessary. 

The fact that the user has access to the `dealerScore` and `playerScore` variables would normally be cause for alarm (they could cheat and edit these values using their browser's developer tools). In this case the values are always set by the server, but it's good to hide sensitive things like this from the user's view.

**Comment by mromphf** [comment]
Merged. Thanks for pointing out that oversight, and thanks for fixing it!
